module.exports = {
	plugins: [ 'stylelint-order' ],
	rules: {
		'at-rule-empty-line-before': [ 'always', {
			'except': [ 'blockless-after-blockless', 'first-nested' ],
			'ignore': [ 'after-comment' ]
		} ],
		'at-rule-name-case': 'lower',
		'at-rule-name-space-after': 'always-single-line',
		'at-rule-no-unknown': [ true, {
			'ignoreAtRules': 'extend'
		} ],
		'at-rule-semicolon-newline-after': 'always',
		'block-closing-brace-newline-after': 'always',
		'block-closing-brace-newline-before': 'always',
		'block-no-empty': true,
		'block-opening-brace-newline-after': 'always',
		'block-opening-brace-space-before': 'always',
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'color-named': 'never',
		'color-no-invalid-hex': true,
		'comment-empty-line-before': [ 'always', {
			except: [ 'first-nested' ],
			ignore: [ 'stylelint-commands' ],
		} ],
		'comment-no-empty': true,
		'declaration-bang-space-after': 'never',
		'declaration-bang-space-before': 'always',
		'declaration-block-no-duplicate-properties': [ true, {
			ignore: [ 'consecutive-duplicates' ],
		} ],
		'declaration-block-semicolon-newline-after': 'always',
		'declaration-block-semicolon-space-before': 'never',
		'declaration-block-trailing-semicolon': 'always',
		'declaration-colon-newline-after': 'always-multi-line',
		'declaration-colon-space-after': 'always-single-line',
		'declaration-colon-space-before': 'never',
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-property-unit-allowed-list': {
			'line-height': [ 'px' ],
		},
		'font-family-name-quotes': 'always-where-recommended',
		'font-family-no-duplicate-names': true,
		'font-family-no-missing-generic-family-keyword': true,
		'font-weight-notation': [ 'numeric', {
			ignore: [ 'relative' ],
		} ],
		'function-calc-no-unspaced-operator': true,
		'function-comma-space-after': 'always',
		'function-comma-space-before': 'never',
		'function-linear-gradient-no-nonstandard-direction': true,
		'function-max-empty-lines': 1,
		'function-name-case': [
			'lower',
			{
				ignoreFunctions: [ '/^DXImageTransform.Microsoft.*$/' ],
			},
		],
		'function-parentheses-space-inside': 'never',
		'function-url-quotes': 'never',
		'function-whitespace-after': 'always',
		indentation: 'tab',
		'keyframe-declaration-no-important': true,
		'length-zero-no-unit': true,
		'linebreaks': 'unix',
		'max-empty-lines': 1,
		'max-line-length': [
			80,
			{
				ignore: 'non-comments',
				ignorePattern: [
					'/(https?://[0-9,a-z]*.*)|(^description\\:.+)|(^tags\\:.+)/i',
				],
			},
		],
		'media-feature-colon-space-after': 'always',
		'media-feature-colon-space-before': 'never',
		'media-feature-name-no-unknown': true,
		'media-feature-range-operator-space-after': 'always',
		'media-feature-range-operator-space-before': 'always',
		'media-query-list-comma-newline-after': 'always-multi-line',
		'media-query-list-comma-space-after': 'always-single-line',
		'media-query-list-comma-space-before': 'never',
		'no-descending-specificity': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-empty-first-line': true,
		'no-empty-source': true,
		'no-eol-whitespace': true,
		'no-extra-semicolons': true,
		'no-invalid-double-slash-comments': true,
		'no-missing-end-of-source-newline': true,
		'number-leading-zero': 'always',
		'number-no-trailing-zeros': true,
		'order/properties-alphabetical-order': true,
		'property-case': 'lower',
		'property-no-unknown': true,
		'rule-empty-line-before': [ 'always', {
			ignore: [ 'after-comment' ],
			except: [ 'first-nested' ],
		} ],
		'selector-attribute-brackets-space-inside': 'never',
		'selector-attribute-operator-space-after': 'never',
		'selector-attribute-operator-space-before': 'never',
		'selector-attribute-quotes': 'always',
		'selector-class-pattern': null,
		'selector-id-pattern': [ '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$', {
			message: 'Selector should use lowercase and separate words with hyphens (selector-id-pattern)',
		} ],
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		'selector-list-comma-newline-after': 'always',
		'selector-list-comma-space-before': 'never',
		'selector-max-empty-lines': 0,
		'selector-pseudo-class-case': 'lower',
		'selector-pseudo-class-no-unknown': true,
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'selector-pseudo-element-case': 'lower',
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-element-no-unknown': true,
		'selector-type-case': 'lower',
		'selector-type-no-unknown': true,
		'string-no-newline': true,
		'string-quotes': 'double',
		'unit-case': 'lower',
		'unit-no-unknown': true,
		'value-keyword-case': 'lower',
		'value-list-comma-newline-after': 'always-multi-line',
		'value-list-comma-space-after': 'always-single-line',
		'value-list-comma-space-before': 'never',
	},
};
